### ISSUE TITLE
カード番号に対応するブランドが複数候補ある場合はUNKNOWNとする

### ISSUE THREAD

**Issue by esmasui** [uPhyca/CreditCardEditText#20]
現状、カード番号が"3"で始まるAMEX, JCB, Dinersを入力するとき、最初の1文字でまずDinersと判定され二文字でAMEX, JCB, Dinersのいずれかが確定する。
この判定ロジックでカード番号の変更に応じてブランドを表示する場合、ユーザーはAMEXのカードを入力しているのに最初の一文字の時点ではDinersと表示されるため混乱を招く。

**Comment by esmasui** [comment]
元のコードのDinersの判定 "^3.*"が雑すぎるために起きた問題。実際は他のカードと同じく2文字目以降も規定されている https://en.wikipedia.org/wiki/Bank_card_number

**Comment by yanzm** [comment]
あう
